
export const EQUIPMENT_TYPES = [
  "Notebook",
  "Smartphone",
  "Desktop PC",
  "Monitor",
  "Teclado/Mouse",
  "Headset",
  "Adaptador/Dock",
  "Tablet"
];

export const BRANDS = [
  "Lenovo",
  "Dell",
  "Apple",
  "HP",
  "Samsung",
  "Motorola",
  "Asus",
  "Logitech",
  "LG",
  "Outra"
];

export const MODELS_LIST = [
  // Notebooks Entry (E-Series)
  "E470",
  "E480",
  "E14 G1",
  "E14 G2",
  "E14 G4",
  "E14 G6",
  
  // Notebooks Premium (T-Series / X-Series)
  "T470",
  "T14 G1",
  "T14 G2",
  "T14 G5",
  "X270",
  "X13 G1",
  "X13 G5",
  
  // Desktops (Tiny)
  "DESKTOP M700",
  "DESKTOP M710q",
  "DESKTOP M720q",
  "DESKTOP M70q G1",
  "DESKTOP M80q",
  "DESKTOP M70q G4",
  
  // Smartphones
  "MOTO G54",
  "MOTO GS5", 
  "SAMSUNG A12",
  "IPHONE 12",
  "IPHONE 14",
  "Outros"
];

// Lista consolidada de processadores reais encontrados nos modelos
export const PROCESSORS_LIST = [
  // Intel Core i5 Antigos
  "Intel® Core™ i5-6200U (6ª Geração)",
  "Intel® Core™ i5-7200U (7ª Geração)",
  "Intel® Core™ i5-6400T (Desktop)",
  "Intel® Core™ i5-7400T (Desktop)",
  
  // Intel Core i5 Quad-Core (8ª - 10ª)
  "Intel® Core™ i5-8250U (8ª Geração)",
  "Intel® Core™ i5-8400T (Desktop)",
  "Intel® Core™ i5-9400T (Desktop)",
  "Intel® Core™ i5-10210U (10ª Geração)",
  "Intel® Core™ i5-10310U vPro® (10ª Geração)",
  "Intel® Core™ i5-10400T (Desktop)",
  "Intel® Core™ i7-10700T vPro® (Desktop)",

  // Intel Core i5/i7 Modernos (11ª - 13ª)
  "Intel® Core™ i5-1135G7 (11ª Geração)",
  "Intel® Core™ i5-1145G7 vPro® (11ª Geração)",
  "Intel® Core™ i5-1235U (12ª Geração)",
  "Intel® Core™ i5-13400T (Desktop)",

  // Intel Core Ultra (AI PCs)
  "Intel® Core™ Ultra 5 125U (AI Boost)",
  "Intel® Core™ Ultra 7 165U (vPro AI)",

  // Mobile Processors
  "MediaTek Dimensity 7020 (Octa-Core)",
  "MediaTek Helio P35 (Octa-Core)",
  "Qualcomm Snapdragon 430 (Octa-Core)",
  "Apple A14 Bionic (Hexa-Core)",
  "Apple A15 Bionic (Hexa-Core)"
];

export const MEMORY_LIST = ["4GB", "8GB", "16GB", "24GB", "32GB", "40GB", "64GB"];

export const STORAGE_LIST = ["64GB", "128GB", "256GB", "480GB", "512GB", "1TB", "2TB"];

// Mapeamento exato de especificações por modelo (Baseado em Padrão Corporativo Comum)
export const MODEL_SPECS: Record<string, { processor: string; memory: string; storage: string }> = {
  // --- NOTEBOOKS LENOVO ---
  "E470": { 
    processor: "Intel® Core™ i5-7200U (7ª Geração)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "E480": { 
    processor: "Intel® Core™ i5-8250U (8ª Geração)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "E14 G1": { 
    processor: "Intel® Core™ i5-10210U (10ª Geração)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "E14 G2": { 
    processor: "Intel® Core™ i5-1135G7 (11ª Geração)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "E14 G4": { 
    processor: "Intel® Core™ i5-1235U (12ª Geração)", 
    memory: "32GB", 
    storage: "1TB" 
  },
  "E14 G6": { 
    processor: "Intel® Core™ Ultra 5 125U (AI Boost)", 
    memory: "32GB", 
    storage: "1TB" 
  },
  
  // --- T-SERIES & X-SERIES ---
  "T470": {
    processor: "Intel® Core™ i5-7200U (7ª Geração)",
    memory: "8GB",
    storage: "256GB"
  },
  "T14 G1": { 
    processor: "Intel® Core™ i5-10310U vPro® (10ª Geração)", 
    memory: "16GB", 
    storage: "256GB" 
  },
  "T14 G2": { 
    processor: "Intel® Core™ i5-1145G7 vPro® (11ª Geração)", 
    memory: "16GB", 
    storage: "512GB" 
  },
  "T14 G5": { 
    processor: "Intel® Core™ Ultra 7 165U (vPro AI)", 
    memory: "16GB", 
    storage: "512GB" 
  },
  "X270": { 
    processor: "Intel® Core™ i5-6200U (6ª Geração)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "X13 G1": {
    processor: "Intel® Core™ i5-10310U vPro® (10ª Geração)",
    memory: "16GB", 
    storage: "256GB"
  },
  "X13 G5": { 
    processor: "Intel® Core™ Ultra 7 165U (vPro AI)", 
    memory: "16GB", 
    storage: "512GB" 
  },

  // --- DESKTOPS LENOVO ---
  "DESKTOP M700": { 
    processor: "Intel® Core™ i5-6400T (Desktop)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "DESKTOP M710q": { 
    processor: "Intel® Core™ i5-7400T (Desktop)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "DESKTOP M720q": { 
    processor: "Intel® Core™ i5-8400T (Desktop)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "DESKTOP M70q G1": { 
    processor: "Intel® Core™ i5-10400T (Desktop)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "DESKTOP M80q": { 
    processor: "Intel® Core™ i7-10700T vPro® (Desktop)", 
    memory: "16GB", 
    storage: "512GB" 
  },
  "DESKTOP M70q G4": { 
    processor: "Intel® Core™ i5-13400T (Desktop)", 
    memory: "16GB", 
    storage: "512GB" 
  },

  // --- SMARTPHONES ---
  "MOTO G54": { 
    processor: "MediaTek Dimensity 7020 (Octa-Core)", 
    memory: "8GB", 
    storage: "256GB" 
  },
  "MOTO GS5": { 
    processor: "Qualcomm Snapdragon 430 (Octa-Core)", 
    memory: "4GB", 
    storage: "64GB" 
  },
  "SAMSUNG A12": { 
    processor: "MediaTek Helio P35 (Octa-Core)", 
    memory: "4GB", 
    storage: "64GB" 
  },
  "IPHONE 12": { 
    processor: "Apple A14 Bionic (Hexa-Core)", 
    memory: "4GB", 
    storage: "128GB" 
  },
  "IPHONE 14": { 
    processor: "Apple A15 Bionic (Hexa-Core)", 
    memory: "6GB", 
    storage: "128GB" 
  }
};

export const MODELS: Record<string, string[]> = {
  "Dell": ["Latitude 5420", "Precision 3561", "OptiPlex 7090", "XPS 13", "Vostro 3400"],
  "Apple": ["MacBook Air M1", "MacBook Pro 14", "iPhone 12", "iPhone 13", "iPhone 14", "iPhone 14 Pro", "iPad Air"],
  "Lenovo": ["ThinkPad T14", "ThinkStation P340", "Yoga Slim 7", "IdeaPad 3", "T14 G5"],
  "HP": ["EliteBook 840", "ProBook 445", "ZBook Firefly", "Pavilion"],
  "Samsung": ["Galaxy S21", "Galaxy S22", "Galaxy A53", "Monitor Odyssey"],
  "Logitech": ["MX Master 3", "K120", "G Pro Wireless", "C922 Pro"],
  "Outra": ["Genérico / Outro"]
};

// Lista de usuários completa para busca local (Parseada do texto fornecido)
export const AD_USERS = [
  { nome: "Adao Costa", email: "adao.costa@ciriontechnologies.com" },
  { nome: "Adary De Souza Junior", email: "adary.souza@ciriontechnologies.com" },
  { nome: "Ademilson Garcia", email: "ademilson.garcia@ciriontechnologies.com" },
  { nome: "Adilson Silva", email: "adilson.silva@ciriontechnologies.com" },
  { nome: "Adriane Gomes Valim Torso", email: "adriane.gomesvalimtorso@ciriontechnologies.com" },
  { nome: "Adriano Bueno Rodrigues", email: "adriano.buenorodrigues@ciriontechnologies.com" },
  { nome: "Adriano Dourado", email: "Adriano.Dourado@ciriontechnologies.com" },
  { nome: "Adriano Vieira", email: "Adriano.Vieira@ciriontechnologies.com" },
  { nome: "Agnes Rios Teixeira de Magalhães", email: "agnes.rios@ciriontechnologies.com" },
  { nome: "Albert Henrique", email: "albert.henrique@ciriontechnologies.com" },
  { nome: "Alberto Alves", email: "alberto.alves@ciriontechnologies.com" },
  { nome: "Alessandra Gusmao", email: "alessandra.gusmao@ciriontechnologies.com" },
  { nome: "Alessandro Sanches", email: "alessandro.sanches@ciriontechnologies.com" },
  { nome: "Alessandro Vieira", email: "alessandro.vieira@ciriontechnologies.com" },
  { nome: "Alex Lima Silva", email: "Alex.Silva@ciriontechnologies.com" },
  { nome: "Alex Rosa", email: "alex.rosa@ciriontechnologies.com" },
  { nome: "Alexander Arrais", email: "alexander.arrais@ciriontechnologies.com" },
  { nome: "Alexandra Breda", email: "alexandra.breda@ciriontechnologies.com" },
  { nome: "Alexandre Alencar", email: "alexandre.alencar@ciriontechnologies.com" },
  { nome: "Alexandre Barros", email: "Alexandre.Barros@ciriontechnologies.com" },
  { nome: "Alexandre Dos Santos Pardo", email: "Alexandre.Pardo@ciriontechnologies.com" },
  { nome: "Alexandre fernandes", email: "alexandre.fernandes@ciriontechnologies.com" },
  { nome: "Alexandre Nogueira", email: "alexandre.nogueira@ciriontechnologies.com" },
  { nome: "Alexandre Pereira Simcsik", email: "alexandre.simcsik@ciriontechnologies.com" },
  { nome: "Alexandre Torejiani", email: "alexandre.torejiani@ciriontechnologies.com" },
  { nome: "Alexandre Watanabe", email: "alexandre.watanabe@ciriontechnologies.com" },
  { nome: "Alice Lobo", email: "alice.lobo@ciriontechnologies.com" },
  { nome: "Aline Aleixo", email: "aline.aleixo@ciriontechnologies.com" },
  { nome: "Aline Santos", email: "aline.santos@ciriontechnologies.com" },
  { nome: "Alisson Tavares", email: "alisson.tavares@ciriontechnologies.com" },
  { nome: "Amadeu Lucas", email: "amadeu.lucas@ciriontechnologies.com" },
  { nome: "Amanda Aldevino", email: "amanda.aldevino@ciriontechnologies.com" },
  { nome: "Amilton Jesus Junior", email: "Amilton.Machado@ciriontechnologies.com" },
  { nome: "Amilton Rodrigues", email: "amilton.rodrigues@ciriontechnologies.com" },
  { nome: "Ana Amarante Fernandes", email: "ana.fernandes@ciriontechnologies.com" },
  { nome: "Ana Amorim", email: "ana.amorim@ciriontechnologies.com" },
  { nome: "Ana Muniz Trebilcock", email: "ana.muniz@ciriontechnologies.com" },
  { nome: "Ana Oliveira", email: "ana.oliveira@ciriontechnologies.com" },
  { nome: "Ana Paula Oliveira", email: "anapaula.oliveira@ciriontechnologies.com" },
  { nome: "Ana Reichert", email: "ana.reichert.ext@ciriontechnologies.com" },
  { nome: "Anderson De Oliveira", email: "anderson.oliveira@ciriontechnologies.com" },
  { nome: "Anderson Pagani Flor", email: "anderson.pagani@ciriontechnologies.com" },
  { nome: "Andre Araujo", email: "Andre.Araujo@ciriontechnologies.com" },
  { nome: "Andre Botelho", email: "andre.botelho.ext@ciriontechnologies.com" },
  { nome: "Andrea Betiol Monteiro Da Silva Bastos", email: "andrea.betiol@ciriontechnologies.com" },
  { nome: "Andrelisi Figuero", email: "andrelisi.figueiro@ciriontechnologies.com" },
  { nome: "Angelo Silva Pereira", email: "angelo.silva@ciriontechnologies.com" },
  { nome: "Anna Almeida", email: "anna.almeida@ciriontechnologies.com" },
  { nome: "Antonio Castro", email: "antonio.castro@ciriontechnologies.com" },
  { nome: "Antonio Vitor Rana", email: "Antonio.Rana@ciriontechnologies.com" },
  { nome: "Ari Aguiar Neto", email: "Ari.Neto@ciriontechnologies.com" },
  { nome: "Artur Martins", email: "artur.martins@ciriontechnologies.com" },
  { nome: "Augusto Barbosa", email: "augusto.barbosa@ciriontechnologies.com" },
  { nome: "Aurelio Souza", email: "Aurelio.Souza@ciriontechnologies.com" },
  { nome: "Barbara Cienna", email: "Barbara.Cienna@ciriontechnologies.com" },
  { nome: "Barbara Santos", email: "barbara.santos@ciriontechnologies.com" },
  { nome: "Basilio Barbosa", email: "basilio.barbosa@ciriontechnologies.com" },
  { nome: "Bruna Farias", email: "bruna.farias@ciriontechnologies.com" },
  { nome: "Bruno Amaral", email: "bruno.amaral@ciriontechnologies.com" },
  { nome: "Bruno Barbosa", email: "Bruno.Barbosa@ciriontechnologies.com" },
  { nome: "Bruno Garcia", email: "Bruno.Garcia@ciriontechnologies.com" },
  { nome: "Bruno Hayashi Batista Komatsu", email: "Bruno.Komatsu@ciriontechnologies.com" },
  { nome: "BRUNO HODGE", email: "bruno.hodge@ciriontechnologies.com" },
  { nome: "Bruno Medeiros De Moraes Carvalho", email: "Bruno.Carvalho@ciriontechnologies.com" },
  { nome: "Bruno Rissi Pezzatto", email: "bruno.pezzatto@ciriontechnologies.com" },
  { nome: "Bruno Souza Leal", email: "Bruno.SouzaLeal@ciriontechnologies.com" },
  { nome: "Camila Leite", email: "camila.leite@ciriontechnologies.com" },
  { nome: "Camila Vellido", email: "camila.vellido.ext@ciriontechnologies.com" },
  { nome: "Carina Oliveira", email: "carina.oliveira@ciriontechnologies.com" },
  { nome: "Carla Lemes", email: "Carla.Lemes@ciriontechnologies.com" },
  { nome: "Carlos augusto Fugi", email: "CarlosAugusto.Fugi@ciriontechnologies.com" },
  { nome: "Carlos De Faria Garcia", email: "Carlos.Defaria@ciriontechnologies.com" },
  { nome: "Carlos De Moraes", email: "Carlos.Moraes@ciriontechnologies.com" },
  { nome: "Carlos Eduardo Nunes Vila Cha", email: "carlos.vilacha@ciriontechnologies.com" },
  { nome: "Carlos Oliveira", email: "carlos2.oliveira@ciriontechnologies.com" },
  { nome: "Carlos Oliveira", email: "carlos.oliveira.ext@ciriontechnologies.com" },
  { nome: "Caroline Sampietri", email: "Caroline.Sampietri@ciriontechnologies.com" },
  { nome: "Cassia Rodrigues De Siqueira", email: "cassia.rodrigues@ciriontechnologies.com" },
  { nome: "Celio Silva Felippe", email: "celio.felippe@ciriontechnologies.com" },
  { nome: "Celso Cassimiro De Araujo", email: "Celso.Araujo@ciriontechnologies.com" },
  { nome: "Cesar Brandini", email: "cesar.brandini@ciriontechnologies.com" },
  { nome: "Chaiane Aichinger", email: "chaiane.aichinger@ciriontechnologies.com" },
  { nome: "Charles Ulguim", email: "charles.ulguim@ciriontechnologies.com" },
  { nome: "Chiara Andolina", email: "chiara.andolina@ciriontechnologies.com" },
  { nome: "Christian Semenoff Grandke", email: "christian.semenoff@ciriontechnologies.com" },
  { nome: "Christian Vanin", email: "cristhian.vanin@ciriontechnologies.com" },
  { nome: "Christina Nowak", email: "christina.nowak@ciriontechnologies.com" },
  { nome: "Cibele Sousa Santos Giarrante", email: "Cibele.Giarrante@ciriontechnologies.com" },
  { nome: "Ciro santos", email: "ciro.santos@ciriontechnologies.com" },
  { nome: "Claudemir Baldo", email: "Claudemir.Baldo@ciriontechnologies.com" },
  { nome: "Claudio Calabrez", email: "claudio.calabrez@ciriontechnologies.com" },
  { nome: "Clayton Bordon", email: "clayton.bordon@ciriontechnologies.com" },
  { nome: "Clayton Hassegawa", email: "clayton.hassegawa@ciriontechnologies.com" },
  { nome: "Cleber Marino Felisberto", email: "Cleber.Marino@ciriontechnologies.com" },
  { nome: "Cleusa De Vasconcelos Da Silveira", email: "Cleusa.Vasconcelos@ciriontechnologies.com" },
  { nome: "Clodoaldo Brito", email: "clodoaldo.faria@ciriontechnologies.com" },
  { nome: "Cristiano Da Silva Brandao", email: "cristiano.brandao@ciriontechnologies.com" },
  { nome: "Cristiano Sousa", email: "Cristiano.Sousa@ciriontechnologies.com" },
  { nome: "Cristina De Mello E Silva", email: "Cristina.Mello@ciriontechnologies.com" },
  { nome: "Cristina Dorneles Delgado", email: "Cristina.Delgado@ciriontechnologies.com" },
  { nome: "Dalton Lima De Souza", email: "Dalton.Souza@ciriontechnologies.com" },
  { nome: "Daniel Frutuoso Da Silva", email: "daniel.frutuoso@ciriontechnologies.com" },
  { nome: "Daniel Lima", email: "daniel.lima@ciriontechnologies.com" },
  { nome: "Daniel Malfinati", email: "daniel.malfinati@ciriontechnologies.com" },
  { nome: "Daniel Ramos", email: "daniel.ribeiro@ciriontechnologies.com" },
  { nome: "Daniel Vigato Da Silva", email: "Daniel.DaSilva@ciriontechnologies.com" },
  { nome: "Danielle Rodrigues Da Rocha", email: "Danielle.Rodrigues@ciriontechnologies.com" },
  { nome: "Danilo Cereza", email: "Danilo.Cereza@ciriontechnologies.com" },
  { nome: "Danilo seicho", email: "danilo.seicho@ciriontechnologies.com" },
  { nome: "Darcio De Paula", email: "Darcio.DePaula@ciriontechnologies.com" },
  { nome: "Davi Da Silva", email: "davi.dasilva@ciriontechnologies.com" },
  { nome: "David Braz", email: "david.nascimento.ext@ciriontechnologies.com" },
  { nome: "David Fernandes Magalhaes", email: "David.FernandesMagalhaes@ciriontechnologies.com" },
  { nome: "Debora rodrigues", email: "debora.rodrigues@ciriontechnologies.com" },
  { nome: "Denis Pissaia", email: "Denis.Pissaia@ciriontechnologies.com" },
  { nome: "Deolino Pereira Da Costa Neto", email: "deolino.pereira@ciriontechnologies.com" },
  { nome: "Diego Borges", email: "diego.borges@ciriontechnologies.com" },
  { nome: "Diego lucas De Morais", email: "diego.morais@ciriontechnologies.com" },
  { nome: "Diego Teixeira Mafra De Oliveira", email: "Diego.TeixeiraMafradeOliveira@ciriontechnologies.com" },
  { nome: "Diogo Malta Neves", email: "Diogo.Neves@ciriontechnologies.com" },
  { nome: "Dirlei De Assis", email: "dirlei.deassis@ciriontechnologies.com" },
  { nome: "Douglas ferreira", email: "douglas.depaivaferreira@ciriontechnologies.com" },
  { nome: "Douglas Lima", email: "Douglas.Lima@ciriontechnologies.com" },
  { nome: "Douglas Pedroni", email: "douglas.pedroni@ciriontechnologies.com" },
  { nome: "Edenilson Schunck", email: "edenilson.schunck@ciriontechnologies.com" },
  { nome: "Edimarcos Neves Silva", email: "Edimarcos.Neves@ciriontechnologies.com" },
  { nome: "Edison Nakashima", email: "edison.nakashima@ciriontechnologies.com" },
  { nome: "Eduardo Carrasco", email: "eduardo.carrasco@ciriontechnologies.com" },
  { nome: "Eduardo Eidy Urakawa", email: "Eduardo.Urakawa@ciriontechnologies.com" },
  { nome: "Eduardo Leao De Freitas", email: "Eduardo.Freitas@ciriontechnologies.com" },
  { nome: "Eduardo Lourenco", email: "eduardo.granado@ciriontechnologies.com" },
  { nome: "Eduardo Pereira De Moura", email: "eduardo.moura@ciriontechnologies.com" },
  { nome: "Eduardo Polking", email: "Eduardo.Polking@ciriontechnologies.com" },
  { nome: "Eduardo Silva", email: "eduardo.silva@ciriontechnologies.com" },
  { nome: "Eduardo Souza", email: "eduardo.souza@ciriontechnologies.com" },
  { nome: "Eduardoaugusto Carneiro", email: "EduardoAugusto.Carneiro@ciriontechnologies.com" },
  { nome: "Elaine Santos", email: "elaine.santos@ciriontechnologies.com" },
  { nome: "Eliana Cristina Tritapepe", email: "eliana.tritapepe@ciriontechnologies.com" },
  { nome: "Eliane Alves De Amorim", email: "Eliane.Amorim@ciriontechnologies.com" },
  { nome: "Eliceu Filho", email: "eliceu.filho@ciriontechnologies.com" },
  { nome: "Eliete Martins", email: "eliete.martins@ciriontechnologies.com" },
  { nome: "Elinaldo Pereira", email: "elinaldo.pereira@ciriontechnologies.com" },
  { nome: "Elton Tiepolo", email: "elton.tiepolo@ciriontechnologies.com" },
  { nome: "Emanoel Silva", email: "emanoel.silva@ciriontechnologies.com" },
  { nome: "Emerson Carneiro Da Silva", email: "emerson.carneiro@ciriontechnologies.com" },
  { nome: "Emmanuela Silva", email: "emmanuela.silva@ciriontechnologies.com" },
  { nome: "Evandro Oliveira", email: "evandro.oliveira@ciriontechnologies.com" },
  { nome: "Fabiano De Oliveira", email: "Fabiano.Oliveira@ciriontechnologies.com" },
  { nome: "Fabiano Gama Damiano", email: "Fabiano.Damiano@ciriontechnologies.com" },
  { nome: "Fabiano Gasparini", email: "Fabiano.Gasparini@ciriontechnologies.com" },
  { nome: "Fabio Azevedo", email: "Fabio.Azevedo@ciriontechnologies.com" },
  { nome: "Fabio Da Silva Ribeiro", email: "Fabio.Ribeiro@ciriontechnologies.com" },
  { nome: "Fabio Favaro", email: "fabio.favaro@ciriontechnologies.com" },
  { nome: "Fabio Santos", email: "fabio.santos@ciriontechnologies.com" },
  { nome: "Fabio Teixeira Simoes", email: "Fabio.Teixeira@ciriontechnologies.com" },
  { nome: "Fabio Villa Real", email: "fabio.villa@ciriontechnologies.com" },
  { nome: "Fadel Matta", email: "Fadel.Matta@ciriontechnologies.com" },
  { nome: "Felipe Chagas", email: "felipe.chagas@ciriontechnologies.com" },
  { nome: "Felipe Do Carmo Souza", email: "felipe.docarmosouza@ciriontechnologies.com" },
  { nome: "Felipe Kamael Coelho Ferreira", email: "felipe.kamael@ciriontechnologies.com" },
  { nome: "Felipe Lino De Souza", email: "Felipe.Lino@ciriontechnologies.com" },
  { nome: "Felipe Pires De Carvalho", email: "felipe.piresdecarvalho@ciriontechnologies.com" },
  { nome: "Felipe Rossi", email: "felipe.rossi@ciriontechnologies.com" },
  { nome: "Felipe Teixeira", email: "felipe.teixeira@ciriontechnologies.com" },
  { nome: "Fernanda Bertino Algebaile Da Silva", email: "fernanda.bertino@ciriontechnologies.com" },
  { nome: "Fernanda Menezes", email: "fernanda.menezes@ciriontechnologies.com" },
  { nome: "Fernanda Souza De Oliveira", email: "fernanda.souza@ciriontechnologies.com" },
  { nome: "Fernando Barlem Ciria", email: "Fernando.Ciria@ciriontechnologies.com" },
  { nome: "Fernando Bilbau", email: "Fernando.BilbauFurtado@ciriontechnologies.com" },
  { nome: "Fernando Da Silva Santos", email: "fernando.dasilva.ext@ciriontechnologies.com" },
  { nome: "Fernando De Almeida Anderson", email: "Fernando.Anderson@ciriontechnologies.com" },
  { nome: "Figueiredo, Fabio", email: "fabio.figueiredo@ciriontechnologies.com" },
  { nome: "Flavia Damasio Canudo", email: "Flavia.Damasio@ciriontechnologies.com" },
  { nome: "Flavio Carpaneses", email: "flavio.carpaneses@ciriontechnologies.com" },
  { nome: "Flavio Neregatto XS05026", email: "flavio.neregatto@ciriontechnologies.com" },
  { nome: "Flavio Rodrigues", email: "Flavio.Rodrigues@ciriontechnologies.com" },
  { nome: "Francisco Alencar", email: "Francisco.Alencar@ciriontechnologies.com" },
  { nome: "Francisco Freitas Anes", email: "Francisco.Anes@ciriontechnologies.com" },
  { nome: "Francisco Fukumoto", email: "francisco.fukumoto@ciriontechnologies.com" },
  { nome: "Francisco Helmo Ribeiro", email: "helmo.ribeiro@ciriontechnologies.com" },
  { nome: "Francisco Magno", email: "francisco.magno@ciriontechnologies.com" },
  { nome: "Francisco Silva Viteri", email: "Francisco.Silva@ciriontechnologies.com" },
  { nome: "Gabriel Barbedo", email: "gabriel.barbedo@ciriontechnologies.com" },
  { nome: "Gabriel Soares", email: "gabriel.soares@ciriontechnologies.com" },
  { nome: "Geraldo Amorim", email: "Geraldo.Amorim@ciriontechnologies.com" },
  { nome: "Geraldo Teixeira", email: "GeraldoM.TeixeiraDaSilva.Filho@ciriontechnologies.com" },
  { nome: "Gilmar Silva", email: "Gilmar.Silva@ciriontechnologies.com" },
  { nome: "Giovana Ribeiro Dos Santos", email: "giovana.santos@ciriontechnologies.com" },
  { nome: "Givanildo Silva", email: "givanildo.silva@ciriontechnologies.com" },
  { nome: "Glaciana Rocha", email: "glaciana.rocha@ciriontechnologies.com" },
  { nome: "Glauco Bertino", email: "glauco.bertino@ciriontechnologies.com" },
  { nome: "Graziela Tondin", email: "graziela.tondin@ciriontechnologies.com" },
  { nome: "Guilherme Aiex", email: "guilherme.aiex@ciriontechnologies.com" },
  { nome: "Guilherme Assis Fernandes De Oliveira", email: "guilherme.assis@ciriontechnologies.com" },
  { nome: "Guilherme Longhi De Carvalho", email: "guilherme.longhi@ciriontechnologies.com" },
  { nome: "Gustavo de Luca", email: "gustavo.deluca@ciriontechnologies.com" },
  { nome: "Gustavo Farro Santos", email: "gustavo.farro@ciriontechnologies.com" },
  { nome: "Gustavo Lourencon", email: "gustavo.lourencon@ciriontechnologies.com" },
  { nome: "Hamilton Mendes", email: "hamilton.mendes@ciriontechnologies.com" },
  { nome: "Hebert Nunes De Souza", email: "Hebert.Nunes@ciriontechnologies.com" },
  { nome: "Helaine Perdigao Oliveira", email: "Helaine.Oliveira@ciriontechnologies.com" },
  { nome: "Henrique Barros", email: "henrique.barros@ciriontechnologies.com" },
  { nome: "Henrique Borges", email: "henrique.borges@ciriontechnologies.com" },
  { nome: "Henrique Brunetti", email: "henrique.brunetti@ciriontechnologies.com" },
  { nome: "henri", email: "heubert.river@ciriontechnologies.com" },
  { nome: "Heubert Mendes Da Costa", email: "heubert.river@ciriontechnologies.com" },
  { nome: "Hugo Mizukami", email: "Hugo.Mizukami@ciriontechnologies.com" },
  { nome: "Igor Lopes Munhoz Montes", email: "Igor.Montes@ciriontechnologies.com" },
  { nome: "Iran Alves De Lima", email: "Iran.Lima@ciriontechnologies.com" },
  { nome: "Isabel Alves Campos", email: "isabel.campos@ciriontechnologies.com" },
  { nome: "Isabelle Arbex", email: "isabelle.arbex@ciriontechnologies.com" },
  { nome: "Israel Moura da Silva", email: "israel.silva@ciriontechnologies.com" },
  { nome: "Izabelita Franca", email: "izabelita.franca@ciriontechnologies.com" },
  { nome: "Jacqueline Castro", email: "jacqueline.castro@ciriontechnologies.com" },
  { nome: "Jacques Lemos Guimaraes", email: "Jacques.LemosGuimaraes@ciriontechnologies.com" },
  { nome: "Janaina Oliveira", email: "Janaina.Oliveira@ciriontechnologies.com" },
  { nome: "Jean lima", email: "jean.lima@ciriontechnologies.com" },
  { nome: "Jeferson Justo", email: "jeferson.justo@ciriontechnologies.com" },
  { nome: "Jennifer De Castro E Silva", email: "jennifer.decastro@ciriontechnologies.com" },
  { nome: "Jennyfer Marangoni", email: "Jennyfer.Marangoni@ciriontechnologies.com" },
  { nome: "Jessica Martimiano", email: "jessica.martimiano.ext@ciriontechnologies.com" },
  { nome: "Jhonis Sousa", email: "jhonis.sousa@ciriontechnologies.com" },
  { nome: "João Batista Gomes Pereira", email: "joao.batista.ext@ciriontechnologies.com" },
  { nome: "Joao Visconti", email: "joao.visconti@ciriontechnologies.com" },
  { nome: "Joao Dos Santos Filho", email: "Joao.Filho@ciriontechnologies.com" },
  { nome: "Joao Luiz Netto", email: "joao.netto@ciriontechnologies.com" },
  { nome: "Joao Menuzzo Semeghini", email: "Joao.Semeghini@ciriontechnologies.com" },
  { nome: "Joao Prandini", email: "joao.prandini@ciriontechnologies.com" },
  { nome: "Jonas Ferrer", email: "jonas.ferrer@ciriontechnologies.com" },
  { nome: "Jonatas Almeida De Jesus", email: "Jonatas.Almeida@ciriontechnologies.com" },
  { nome: "Jonathan Corazzari Rodrigues", email: "Jonathan.Corazzari@ciriontechnologies.com" },
  { nome: "Jone Pacheco", email: "jone.pacheco@ciriontechnologies.com" },
  { nome: "Jorge Fernando Rocha Silva", email: "jorge.rocha@ciriontechnologies.com" },
  { nome: "Jorge Luiz Alves Dias", email: "Jorge.LuizAlvesDias@ciriontechnologies.com" },
  { nome: "Jorge marco Cabezas Pacheco", email: "jorge.pacheco@ciriontechnologies.com" },
  { nome: "Jose Boffe", email: "paulo.boffe@ciriontechnologies.com" },
  { nome: "Jose Brito", email: "jose.brito@ciriontechnologies.com" },
  { nome: "Jose Castelucci Morone", email: "Jose.Morone@ciriontechnologies.com" },
  { nome: "Jose Da Silva", email: "jose.silva15@ciriontechnologies.com" },
  { nome: "Jose De Barros", email: "jose.debarros@ciriontechnologies.com" },
  { nome: "Jose De Oliveira Moreira", email: "jose.moreira@ciriontechnologies.com" },
  { nome: "Jose Geovane Alves Dias", email: "jose.dias@ciriontechnologies.com" },
  { nome: "Jose Geraldo", email: "Jose.Geraldo@ciriontechnologies.com" },
  { nome: "Jose Magalhaes", email: "jose.magalhaes@ciriontechnologies.com" },
  { nome: "Jose menegale", email: "jose.menegale@ciriontechnologies.com" },
  { nome: "Jose Pivotto Ramos", email: "jose.pivotto@ciriontechnologies.com" },
  { nome: "Jose Roberto Da Silva", email: "jose.roberto@ciriontechnologies.com" },
  { nome: "Jose Roberto de Miranda Russo", email: "jose.russo@ciriontechnologies.com" },
  { nome: "Jose Ruggieri", email: "jose.ruggieri@ciriontechnologies.com" },
  { nome: "Josiane Okasaki", email: "josiane.okasaki@ciriontechnologies.com" },
  { nome: "Julia Fabiane Horst", email: "julia.fabiane@ciriontechnologies.com" },
  { nome: "Juliana Azevedo", email: "juliana.azevedo.ext@ciriontechnologies.com" },
  { nome: "Juliano Fumes Dos Santos", email: "Juliano.Santos@ciriontechnologies.com" },
  { nome: "Juliano Mesquita", email: "Juliano.Mesquita@ciriontechnologies.com" },
  { nome: "Julio Goncalves", email: "julio.goncalves@ciriontechnologies.com" },
  { nome: "Julio Lopes Da Silva", email: "julio.lopesdasilva@ciriontechnologies.com" },
  { nome: "Julio Marcos Gabriel", email: "julio.gabriel@ciriontechnologies.com" },
  { nome: "Julio Oliveira", email: "julio.fernandes@ciriontechnologies.com" },
  { nome: "Julio Pereira", email: "julio.pereira@ciriontechnologies.com" },
  { nome: "Karen Akemi Abe", email: "karen.abe@ciriontechnologies.com" },
  { nome: "Kelvin Lucas", email: "kelvin.lucas@ciriontechnologies.com" },
  { nome: "Kleber Bassetto", email: "kleber.bassetto@ciriontechnologies.com" },
  { nome: "Lazaro Bagdadi", email: "lazaro.bagdadi@ciriontechnologies.com" },
  { nome: "Leandro Almeida de jesus", email: "leandro.almeida@ciriontechnologies.com" },
  { nome: "Leandro Branco", email: "leandro.branco@ciriontechnologies.com" },
  { nome: "Leandro dos santos", email: "leandro.mathes@ciriontechnologies.com" },
  { nome: "Leandro Ribeiro", email: "Leandro.Ribeiro@ciriontechnologies.com" },
  { nome: "Leandro Rodrigues De Oliveira", email: "leandro.oliveira@ciriontechnologies.com" },
  { nome: "Leandro Yamamoto", email: "leandro.yamamoto@ciriontechnologies.com" },
  { nome: "Leonardo Camara", email: "leonardo.camara@ciriontechnologies.com" },
  { nome: "Leonardo Goncalves Pimentel", email: "Leonardo.Pimentel@ciriontechnologies.com" },
  { nome: "Leopoldo Silva", email: "Leopoldo.Henrique@ciriontechnologies.com" },
  { nome: "Leticia Moreira", email: "leticia.moreira.ext@ciriontechnologies.com" },
  { nome: "Paulo Goncalves", email: "paulo.goncalves@ciriontechnologies.com" },
  { nome: "Juliana Correa", email: "juliana.correa@ciriontechnologies.com" },
  { nome: "Lourdes Cristiane Salgado Carpin", email: "lourdescristiane.salgadocarpin@ciriontechnologies.com" },
  { nome: "Luciana Alves", email: "luciana.alves@ciriontechnologies.com" },
  { nome: "Luciana Bardo", email: "luciana.bardo@ciriontechnologies.com" },
  { nome: "Luciana Da Silva Ferreira", email: "luciana.ferreira@ciriontechnologies.com" },
  { nome: "Luciana Porto", email: "luciana.porto@ciriontechnologies.com" },
  { nome: "Luciana Vilela XS04970", email: "luciana.vilela@ciriontechnologies.com" },
  { nome: "Luciane Martins", email: "Luciane.Martins@ciriontechnologies.com" },
  { nome: "Luciano Da Silva Lara", email: "Luciano.Lara@ciriontechnologies.com" },
  { nome: "Luciano Siqueira", email: "siqueira.luciano@ciriontechnologies.com" },
  { nome: "Luciano Soares", email: "luciano.soares@ciriontechnologies.com" },
  { nome: "Luciano Xavier", email: "luciano.xavier.ext@ciriontechnologies.com" },
  { nome: "Lucilene Muniz", email: "lucilene.muniz@ciriontechnologies.com" },
  { nome: "Luiz Brizzi Santos", email: "luiz.brizzisantos@ciriontechnologies.com" },
  { nome: "Luiz Caputo Da Silva", email: "Luiz.Caputo@ciriontechnologies.com" },
  { nome: "Luiz De Oliveira", email: "luiz.deoliveira@ciriontechnologies.com" },
  { nome: "Luiz Ramos", email: "Luiz.Ramos@ciriontechnologies.com" },
  { nome: "Luiz Reschke", email: "luiz.reschke@ciriontechnologies.com" },
  { nome: "Luiz Rodrigues", email: "luiz.rodrigues@ciriontechnologies.com" },
  { nome: "Luiz Sales Carneiro", email: "Luiz.SalesCarneiro@ciriontechnologies.com" },
  { nome: "Luiz Teixeira Gomes", email: "Luiz.Gomes@ciriontechnologies.com" },
  { nome: "Luizfernando Silva", email: "LuizFernando.Silva@ciriontechnologies.com" },
  { nome: "Magnus Fischer", email: "magnus.fischer@ciriontechnologies.com" },
  { nome: "Maira Fraile", email: "maira.fraile@ciriontechnologies.com" },
  { nome: "Marcelo Amati", email: "marcelo.amati@ciriontechnologies.com" },
  { nome: "Marcelo Da Costa", email: "marcelo.xavier@ciriontechnologies.com" },
  { nome: "Marcelo De Almeida", email: "marcelo.dealmeida@ciriontechnologies.com" },
  { nome: "Marcelo De Oliveira", email: "Marcelo.Delfraro@ciriontechnologies.com" },
  { nome: "Marcelo De Queiroz", email: "Marcelo.Queiroz@ciriontechnologies.com" },
  { nome: "Marcelo de Rezende", email: "marcelo.rezende@ciriontechnologies.com" },
  { nome: "Marcelo Henrique Elias", email: "Marcelo.Henrique@ciriontechnologies.com" },
  { nome: "Marcelo Gomes", email: "marcelo.gomes@ciriontechnologies.com" },
  { nome: "Marcelo Guerreiro Da Silva", email: "Marcelo.Guerreiro@ciriontechnologies.com" },
  { nome: "Marcelo Guido", email: "Marcelo.Guido@ciriontechnologies.com" },
  { nome: "Marcelo Halas", email: "marcelo.halas@ciriontechnologies.com" },
  { nome: "Marcelo Kozeminski", email: "marcelo.kozeminski@ciriontechnologies.com" },
  { nome: "Marcelo Monteiro Fatigati", email: "Marcelo.Fatigati@ciriontechnologies.com" },
  { nome: "Marcelo Thomaz", email: "Marcelo.Thomaz@ciriontechnologies.com" },
  { nome: "Marcia Silvi Barros", email: "marcia.silvi@ciriontechnologies.com" },
  { nome: "Marciel Dos Santos", email: "Marciel.Santos@ciriontechnologies.com" },
  { nome: "Marcio Belezi", email: "marcio.belezi@ciriontechnologies.com" },
  { nome: "Marcio Paiva", email: "marcio.paiva@ciriontechnologies.com" },
  { nome: "Marcio Tressmann", email: "marcio.tressmann@ciriontechnologies.com" },
  { nome: "Marco Perez", email: "Marco.Perez@ciriontechnologies.com" },
  { nome: "Marco Pinheiro", email: "marco.pinheiro@ciriontechnologies.com" },
  { nome: "Marcos Dos Anjos E Silva", email: "Marcos.DosAnjosESilva@ciriontechnologies.com" },
  { nome: "Marcos Malfatti", email: "Marcos.Malfatti@ciriontechnologies.com" },
  { nome: "Marcos Marchetti", email: "marcos.marchetti@ciriontechnologies.com" },
  { nome: "Marcos Maulli De Jesus", email: "marcos.maullidejesus@ciriontechnologies.com" },
  { nome: "Marcos Peixoto De Oliveira", email: "marcos.peixoto@ciriontechnologies.com" },
  { nome: "Marcos Silva Firmo", email: "Marcos.Firmo@ciriontechnologies.com" },
  { nome: "Marcus Dutra De Padua", email: "marcus.dutra@ciriontechnologies.com" },
  { nome: "Mariana Parmegiani Serpa", email: "mariana.ong@ciriontechnologies.com" },
  { nome: "Marlon Meira", email: "marlon.meira@ciriontechnologies.com" },
  { nome: "Marlon Rocha", email: "marlon.rocha@ciriontechnologies.com" },
  { nome: "Matheus Carmo", email: "Matheus.Carmo@ciriontechnologies.com" },
  { nome: "Mauricio Colombo", email: "mauricio.colombo@ciriontechnologies.com" },
  { nome: "Mauricio Cymerman", email: "mauricio.cymerman@ciriontechnologies.com" },
  { nome: "Mauricio Iuras", email: "mauricio.iuras@ciriontechnologies.com" },
  { nome: "Mauricio Kazushi Goto", email: "Mauricio.Goto@ciriontechnologies.com" },
  { nome: "Mauricio Lima", email: "mauricio.lima@ciriontechnologies.com" },
  { nome: "Mauricio Maia", email: "mauricio.maia@ciriontechnologies.com" },
  { nome: "Mauricio Marques", email: "Mauricio.Marques@ciriontechnologies.com" },
  { nome: "Mauricio Merlino", email: "Mauricio.Merlino@ciriontechnologies.com" },
  { nome: "Mauricio Rodrigues Da Silva", email: "Mauricio.Silva@ciriontechnologies.com" },
  { nome: "Mauricio Sugui", email: "mauricio.sugui@ciriontechnologies.com" },
  { nome: "Mauro Mendes", email: "mauro.mendes@ciriontechnologies.com" },
  { nome: "Michael De Sousa Shibuya", email: "Michael.DeSousaShibuya@ciriontechnologies.com" },
  { nome: "Milena Jeronimo Dos Santos", email: "Milena.JeronimodosSantos@ciriontechnologies.com" },
  { nome: "Milena Muniz", email: "Milena.Muniz@ciriontechnologies.com" },
  { nome: "Mirella Esteves", email: "Mirella.Esteves@ciriontechnologies.com" },
  { nome: "Misael Soares", email: "misael.soares@ciriontechnologies.com" },
  { nome: "Moacir Dantas", email: "moacir.dantas@ciriontechnologies.com" },
  { nome: "Monica Borges", email: "monica.borges@ciriontechnologies.com" },
  { nome: "Carvalho Muller, Alexandre", email: "alexandre.muller@ciriontechnologies.com" },
  { nome: "Munique Hess", email: "Munique.Hess@ciriontechnologies.com" },
  { nome: "Muriel Marinho", email: "muriel.espirito@ciriontechnologies.com" },
  { nome: "Murillo Silveira", email: "murillo.silveira@ciriontechnologies.com" },
  { nome: "Murilo Bustamante", email: "murilo.bustamante@ciriontechnologies.com" },
  { nome: "Murilo Silva", email: "murilo.silva@ciriontechnologies.com" },
  { nome: "Natalia Francielly Pereira De Oliviera", email: "natalia.francielly@ciriontechnologies.com" },
  { nome: "Nathalie Calafiori", email: "nathalie.calafiori@ciriontechnologies.com" },
  { nome: "Nelma Jocinete Dos Santos", email: "Nelma.Santos@ciriontechnologies.com" },
  { nome: "Nivaldo Carvalho", email: "nivaldo.carvalho@ciriontechnologies.com" },
  { nome: "Odair Ribeiro", email: "odair.ribeiro@ciriontechnologies.com" },
  { nome: "Pamela Spadrezani", email: "pamela.spadrezani@ciriontechnologies.com" },
  { nome: "Paula De Oliveira Ribeiro Costa", email: "Paula.Costa@ciriontechnologies.com" },
  { nome: "Paula Vivo Chaneton", email: "paula.vivo@ciriontechnologies.com" },
  { nome: "Paulo Bononi", email: "Paulo.Bononi@ciriontechnologies.com" },
  { nome: "Paulo Chediac", email: "Paulo.Chediac@ciriontechnologies.com" },
  { nome: "Paulo Medeiros", email: "paulo.medeiros@ciriontechnologies.com" },
  { nome: "Paulo Oliveira", email: "paulo.oliveira@ciriontechnologies.com" },
  { nome: "Paulo Selotto", email: "paulo.selotto@ciriontechnologies.com" },
  { nome: "Pedro Soares", email: "pedro.soares@ciriontechnologies.com" },
  { nome: "Pedro Weiss De Andrade", email: "pedro.weiss@ciriontechnologies.com" },
  { nome: "Pedro henrique Real", email: "pedrohenrique.real@ciriontechnologies.com" },
  { nome: "Plantão Backbone COTIA", email: "plantaobackboneCOTIA@ciriontechnologies.com" },
  { nome: "plantão equipe de segurança", email: "plantaoSOC@ciriontechnologies.com" },
  { nome: "Plantão subestação COTIA", email: "plataosubestacao@ciriontechnologies.com" },
  { nome: "Plantão subestação COTIA", email: "plataoSUBCOTIA@ciriontechnologies.com" },
  { nome: "Plinio Rodrigues", email: "plinio.rodrigues@ciriontechnologies.com" },
  { nome: "Priscila De Melo", email: "priscila.dossantos@ciriontechnologies.com" },
  { nome: "Priscila Naki", email: "priscila.naki@ciriontechnologies.com" },
  { nome: "Quelen De Carvalho Sommer", email: "Quelen.Sommer@ciriontechnologies.com" },
  { nome: "Queler Ferreira", email: "Queler.Ferreira@ciriontechnologies.com" },
  { nome: "Rafael De Macedo Soares", email: "rafael.demacedo@ciriontechnologies.com" },
  { nome: "Rafael Ribeiro De Souza", email: "Rafael.RibeiroDeSouza@ciriontechnologies.com" },
  { nome: "Rafael Teotonio Ricarte", email: "rafael.ricarte@ciriontechnologies.com" },
  { nome: "Rafael Tognolli", email: "rafael.tognolli@ciriontechnologies.com" },
  { nome: "Rafael Velasques", email: "rafael.velasques@ciriontechnologies.com" },
  { nome: "Raphael Inacio", email: "raphael.inacio@ciriontechnologies.com" },
  { nome: "Raphael Vieira", email: "raphael.vieira@ciriontechnologies.com" },
  { nome: "Raphael Zara", email: "Raphael.Zara@ciriontechnologies.com" },
  { nome: "Raquel Pepineli Cabral", email: "Raquel.PepineliCabral@ciriontechnologies.com" },
  { nome: "Reginaldo Ferreira", email: "reginaldo.ferreira@ciriontechnologies.com" },
  { nome: "Reginaldo Gomes", email: "reginaldo.gomes@ciriontechnologies.com" },
  { nome: "Reinaldo Da Silva", email: "Reinaldo.Silva@ciriontechnologies.com" },
  { nome: "Rejane Alapenha", email: "rejane.alapenha@ciriontechnologies.com" },
  { nome: "Rejane De jesus dias", email: "Rejane.DeJesusDias@ciriontechnologies.com" },
  { nome: "Renan Lourenco", email: "renan.lourenco@ciriontechnologies.com" },
  { nome: "Renan Ribeiro Rodrigues", email: "Renan.Rodrigues@ciriontechnologies.com" },
  { nome: "Renata Pinto Teles", email: "renata.teles@ciriontechnologies.com" },
  { nome: "Renato Eleoterio Dos Santos", email: "renato.eleoterio@ciriontechnologies.com" },
  { nome: "Renato Hirano", email: "renato.hirano@ciriontechnologies.com" },
  { nome: "Renato Martins", email: "renato.martinsdasilva@ciriontechnologies.com" },
  { nome: "Renato tocaxelli", email: "renato.tocaxelli@ciriontechnologies.com" },
  { nome: "Rene Yoshida Da Rocha", email: "Rene.Yoshida@ciriontechnologies.com" },
  { nome: "Ricardo Andrade Paiva", email: "Ricardo.Paiva@ciriontechnologies.com" },
  { nome: "Ricardo Horesh Gagliano", email: "Ricardo.Gagliano@ciriontechnologies.com" },
  { nome: "Ricardo Lima Manganelli", email: "Ricardo.Manganelli@ciriontechnologies.com" },
  { nome: "Ricardo Munhoz", email: "ricardo.munhoz@ciriontechnologies.com" },
  { nome: "Ricardo Norio Arakaki", email: "Ricardo.Norio@ciriontechnologies.com" },
  { nome: "Ricardo Pimentel", email: "Ricardo.Pimentel@ciriontechnologies.com" },
  { nome: "Ricardo Renno", email: "ricardo.geraldo@ciriontechnologies.com" },
  { nome: "Ricardo Souza", email: "ricardo.souza@ciriontechnologies.com" },
  { nome: "Rita Molina", email: "Rita.Molina@ciriontechnologies.com" },
  { nome: "Roberto Correia De Araujo", email: "Roberto.Correia@ciriontechnologies.com" },
  { nome: "Roberto Maia", email: "Roberto.Maia@ciriontechnologies.com" },
  { nome: "Roberto Pimentel", email: "roberto.pimentel@ciriontechnologies.com" },
  { nome: "Roberto Riveros Gamarra", email: "roberto.gamarra@ciriontechnologies.com" },
  { nome: "Roberto Rosa", email: "roberto.rosa@ciriontechnologies.com" },
  { nome: "Robinson Kussunoki", email: "robinson.kussunoki@ciriontechnologies.com" },
  { nome: "Robson Fante", email: "robson.fante@ciriontechnologies.com" },
  { nome: "Robson Toqueiro", email: "robson.toqueiro@ciriontechnologies.com" },
  { nome: "Rodney Narazzaki", email: "rodney.narazzaki@ciriontechnologies.com" },
  { nome: "Rodolfo Benevides", email: "rodolfo.benevides@ciriontechnologies.com" },
  { nome: "Rodolfo Luiz Leite Rodrigues", email: "Rodolfo.LuizLeiteRodrigues@ciriontechnologies.com" },
  { nome: "Rodrigo Bueno", email: "Rodrigo.Bueno@ciriontechnologies.com" },
  { nome: "Rodrigo Capelare", email: "Rodrigo.Capelare@ciriontechnologies.com" },
  { nome: "Rodrigo De Freitas Gallina", email: "Rodrigo.Gallina@ciriontechnologies.com" },
  { nome: "Rodrigo Lima", email: "rodrigo.lima@ciriontechnologies.com" },
  { nome: "Rodrigo Mastropietro", email: "rodrigo.mastropietro@ciriontechnologies.com" },
  { nome: "Rodrigo Oliveira", email: "rodrigo.oliveira@ciriontechnologies.com" },
  { nome: "Rodrigo Oyakawa", email: "rodrigo.oyakawa@ciriontechnologies.com" },
  { nome: "Rodrigo Pereira", email: "rodrigo.martins@ciriontechnologies.com" },
  { nome: "Rodrigo Perez", email: "rodrigo.perez@ciriontechnologies.com" },
  { nome: "Rogerio Da Silva Barbosa", email: "rogerio.barbosa@ciriontechnologies.com" },
  { nome: "Rogerio Gatti Pereira Da Silva", email: "Rogerio.Silva@ciriontechnologies.com" },
  { nome: "Romilda Gomes", email: "romilda.gomes@ciriontechnologies.com" },
  { nome: "Romulo De Moraes Cillo", email: "Romulo.Cillo@ciriontechnologies.com" },
  { nome: "Ronaldo Da Silva", email: "ronaldo.dasilva@ciriontechnologies.com" },
  { nome: "Ronaldo Dos Santos Araujo", email: "Ronaldo.Araujo@ciriontechnologies.com" },
  { nome: "Roney Viana", email: "roney.viana@ciriontechnologies.com" },
  { nome: "Rozeval Garces", email: "rozeval.garces@ciriontechnologies.com" },
  { nome: "Rubens Pereira Moraes Da Silva", email: "rubens.moraes@ciriontechnologies.com" },
  { nome: "Rubia Carolina Meira De Lima", email: "rubia.lima@ciriontechnologies.com" },
  { nome: "Rui Brito", email: "rui.brito@ciriontechnologies.com" },
  { nome: "Samia Abou Mahmoud", email: "samia.abou@ciriontechnologies.com" },
  { nome: "Sandro Pacheco", email: "Sandro.Pacheco@ciriontechnologies.com" },
  { nome: "Selma Silva Moreira", email: "selma.silva@ciriontechnologies.com" },
  { nome: "Sergio Camargo", email: "sergio.camargo@ciriontechnologies.com" },
  { nome: "Silvia Kakuma", email: "silvia.kakuma@ciriontechnologies.com" },
  { nome: "Silvio Bonete Prestes", email: "silvio.bonete@ciriontechnologies.com" },
  { nome: "Simone Bini Pierdona Marques", email: "Simone.Pierdona@ciriontechnologies.com" },
  { nome: "Stefanie Prado", email: "stefanie.prado@ciriontechnologies.com" },
  { nome: "Suellen Stamm De Sa", email: "suellen.desa@ciriontechnologies.com" },
  { nome: "Sybelle Rossato", email: "sybelle.rossato@ciriontechnologies.com" },
  { nome: "Tabata Pimentel", email: "Tabata.Pimentel@ciriontechnologies.com" },
  { nome: "Tadeu Sidnei Santos Barbosa Da Silva", email: "tadeu.sidnei@ciriontechnologies.com" },
  { nome: "Talita de Simone", email: "talita.desimone@ciriontechnologies.com" },
  { nome: "Talles Pessoa De Almeida Ferreira", email: "Talles.Pessoa@ciriontechnologies.com" },
  { nome: "Tanio De Oliveira Simoes", email: "Tanio.Simoes@ciriontechnologies.com" },
  { nome: "Tatiana Fonseca", email: "Tatiana.Fonseca@ciriontechnologies.com" },
  { nome: "Tatiane Vona", email: "tatiane.vona@ciriontechnologies.com" },
  { nome: "Teresa Fukasawa", email: "teresa.fukasawa@ciriontechnologies.com" },
  { nome: "Thamiris Carvalho", email: "thamiris.carvalho@ciriontechnologies.com" },
  { nome: "Thayane Feltrim De Melo", email: "thayane.feltrimdemelo@ciriontechnologies.com" },
  { nome: "Thiago Archas", email: "thiago.archas@ciriontechnologies.com" },
  { nome: "Thiago Ferraz", email: "Thiago.Ferraz@ciriontechnologies.com" },
  { nome: "Thiago Peranton", email: "thiago.peranton@ciriontechnologies.com" },
  { nome: "Thiago Sanches", email: "thiago.sanches@ciriontechnologies.com" },
  { nome: "Tomio Carvalho Endo", email: "tomio.carvalho@ciriontechnologies.com" },
  { nome: "Uirassu Carvalho Vieira", email: "Uirassu.Vieira@ciriontechnologies.com" },
  { nome: "Ulysses Silveira Junior", email: "Ulysses.Calsavara@ciriontechnologies.com" },
  { nome: "Uriel Souza", email: "uriel.souza@ciriontechnologies.com" },
  { nome: "Valdir Jose Da Rocha", email: "ValdirJose.DaRocha@ciriontechnologies.com" },
  { nome: "Valdivino Oliveira", email: "valdivino.oliveira@ciriontechnologies.com" },
  { nome: "Vander Almeida", email: "vander.almeida@ciriontechnologies.com" },
  { nome: "Vanessa Nunes", email: "Vanessa.Nunes@ciriontechnologies.com" },
  { nome: "Veronica Espinoza", email: "veronica.espinoza2@ciriontechnologies.com" },
  { nome: "Vinicius Flavio", email: "vinicius.flavio@ciriontechnologies.com" },
  { nome: "Vinicius Oliveira", email: "vinicius.oliveira@ciriontechnologies.com" },
  { nome: "Vinicius Oliveira 1", email: "vinicius.oliveira1@ciriontechnologies.com" },
  { nome: "Vitor Alves", email: "vitor.alves.ext@ciriontechnologies.com" },
  { nome: "Vivian Credmann", email: "vivian.craveiro@ciriontechnologies.com" },
  { nome: "Viviane Meirelles", email: "Viviane.Meirelles@ciriontechnologies.com" },
  { nome: "Vladmir Oliveira Rossi", email: "Vladmir.Rossi@ciriontechnologies.com" },
  { nome: "Voloi Borges", email: "voloi.borges@ciriontechnologies.com" },
  { nome: "Wagner Lacerda Cabral", email: "wagner.lacerda@ciriontechnologies.com" },
  { nome: "Wagner Pereira", email: "wagner.pereira@ciriontechnologies.com" },
  { nome: "Wagner xavier", email: "wagner.xavier@ciriontechnologies.com" },
  { nome: "Walter Almeida", email: "walter.almeida@ciriontechnologies.com" },
  { nome: "Wander Watanabe Junior", email: "wander.junior@ciriontechnologies.com" },
  { nome: "Wanderley Silva", email: "wanderley.silva@ciriontechnologies.com" },
  { nome: "Wellington Souza", email: "wellington.souza@ciriontechnologies.com" },
  { nome: "Widson Cardoso Dos Santos", email: "widson.cardoso@ciriontechnologies.com" },
  { nome: "William Domingues", email: "william.domingues@ciriontechnologies.com" },
  { nome: "Willian Sakamoto", email: "willian.sakamoto@ciriontechnologies.com" },
  { nome: "Willian Talon", email: "willian.talon@ciriontechnologies.com" },
  { nome: "Willian Theodoro", email: "william.theodoro@ciriontechnologies.com" },
  { nome: "Yuri Moraes", email: "yuri.moraes@ciriontechnologies.com" },
  { nome: "Yuri Rezende Menck", email: "Yuri.Menck@ciriontechnologies.com" },
  { nome: "Bruno Campos", email: "bruno.campos@ciriontechnologies.com" },
  { nome: "Elvis da Silva", email: "elvis.dasilva.ext@ciriontechnologies.com" },
  { nome: "Rafael Ribeiro de Souza", email: "rafael.ribeirodesouza@ciriontechnologies.com" },
  { nome: "Adauto Melquiades dos Santos", email: "adauto.melquiades@ciriontechnologies.com" },
  { nome: "Regiane Teixeira", email: "regiane.teixeira.ext@ciriontechnologies.com" },
  { nome: "Antonio França", email: "antonio.franca@ciriontechnologies.com" },
  { nome: "Felipe Araújo Sebastião Arnaldo", email: "felipe.araujo@ciriontechnologies.com" },
  { nome: "Santiago Peres Castano", email: "santiago.castano@ciriontechnologies.com" },
  { nome: "Renato Lima da Silva", email: "renato.lima@ciriontechnologies.com" },
  { nome: "Talita Silberman", email: "talita.silberman@ciriontechnologies.com" },
  { nome: "Jessica Costa Silva", email: "jessica.costasilva@ciriontechnologies.com" },
  { nome: "Ana Escobar da Silva", email: "ana.escobar@ciriontechnologies.com" },
  { nome: "William Campos Niche", email: "william.camposniche@ciriontechnologies.com" },
  { nome: "Lelis Pinheiro", email: "lelis.pinheiro@ciriontechnologies.com" },
  { nome: "Carlos Eduardo De Moraes", email: "carlos.moraes@ciriontechnologies.com" },
  { nome: "Fabio da Silva Oliveira", email: "fabio.oliveira@ciriontechnologies.com" },
  { nome: "Aldo Rodrigo De Melo", email: "aldo.melo@ciriontechnologies.com" },
  { nome: "Jose Fischer", email: "jose.fischer@ciriontechnologies.com" },
  { nome: "Rubens Perez Monteiro", email: "rubens.perezmonteiro@ciriontechnologies.com" },
  { nome: "Robson Nunes dos Santos", email: "robson.nunesdossantos@ciriontechnologies.com" },
  { nome: "Rodrigo Gagliardi Maciel Da Cruz", email: "rodrigo.cruz@ciriontechnologies.com" },
  { nome: "Victor da Silva Andrade Araujo", email: "victor.dasilvaandradearaujo@ciriontechnologies.com" },
  { nome: "Andre Oliveira", email: "andre.oliveira@ciriontechnologies.com" },
  { nome: "Pablo Dutra", email: "pablo.dutra.ext@ciriontechnologies.com" },
  { nome: "Ederson Dos Santos Gouveia", email: "ederson.dossantos@ciriontechnologies.com" },
  { nome: "Priscila Palma", email: "priscila.palma.ext@ciriontechnologies.com" },
  { nome: "Luciana Polastrini", email: "luciana.polastrini.ext@ciriontechnologies.com" },
  { nome: "Daniel Santos", email: "daniel.santos@ciriontechnologies.com" },
  { nome: "JULIANA CARVALHO DE MELO", email: "juliana.demelo.ext@ciriontechnologies.com" },
  { nome: "Elinalva Lopes Silva", email: "elinalva.lopessilva@ciriontechnologies.com" },
  { nome: "Angelina Nascimento", email: "angelina.nascimento@ciriontechnologies.com" },
  { nome: "MOZAIR COSTA", email: "mozair.costa.ext@ciriontechnologies.com" },
  { nome: "ALEXANDRE BORGES", email: "alexandre.borges@ciriontechnologies.com" },
  { nome: "Bianca Lopez", email: "bianca.lopes.ext@ciriontechnologies.com" },
  { nome: "Renan Marazo", email: "renan.marazo@ciriontechnologies.com" },
  { nome: "Mauro Gomes", email: "mauro.gomes@ciriontechnologies.com" },
  { nome: "Gabrielle Reis", email: "gabrielle.reis.ext@ciriontechnologies.com" },
  { nome: "Jefferson Lisboa Melo", email: "jefferson.melo@ciriontechnologies.com" },
  { nome: "Felipe Augusto de Souza", email: "felipe.augustodesouza@ciriontechnologies.com" },
  { nome: "Panagiotis Xylaras", email: "panagiotis.Xylaras@ciriontechnologies.com" },
  { nome: "Darcio Gilson das Neves", email: "darcio.gilsondasneves@ciriontechnologies.com" },
  { nome: "Windson Gomes Hora", email: "windson.gomeshora.ext@ciriontechnologies.com" },
  { nome: "Ellen Cristina de Souza", email: "ellen.souza.ext@ciriontechnologies.com" },
  { nome: "Danilo Silva Santos", email: "danilo.silva.ext@ciriontechnologies.com" },
  { nome: "Maria Lucia F. Lopes", email: "marialucia.ferreiralopes.ext@ciriontechnologies.com" },
  { nome: "Juliana F. Nascimento", email: "juliana.do.ext@ciriontechnologies.com" },
  { nome: "Mariana Baptista", email: "mariana.baptista.ext@ciriontechnologies.com" },
  { nome: "Beatriz Justo dos Santos", email: "beatriz.santos.ext@ciriontechnologies.com" },
  { nome: "Jessica de J. Oliveira", email: "jessica.oliveira.ext@ciriontechnologies.com" },
  { nome: "Jose Carlos Ruiz", email: "jose.ruiz.ext@ciriontechnologies.com" },
  { nome: "David Acassio da Silva", email: "david.acassio.ext@ciriontechnologies.com" },
  { nome: "Juliana C. Melo", email: "juliana.demelo.ext@ciriontechnologies.com" },
  { nome: "Matheus Silva Marchetti", email: "matheus.marchetti.ext@ciriontechnologies.com" },
  { nome: "Leonardo B. Gomes", email: "leonardo.beranger.ext@ciriontechnologies.com" },
  { nome: "Nilton Carrilo Teixeira da Silva", email: "nilton.teixeiradasilva.ext@ciriontechnologies.com" },
  { nome: "Samanta Bispo", email: "samantha.bispo.ext@ciriontechnologies.com" },
  { nome: "Ariel de Sa Machado", email: "ariel.machado.ext@ciriontechnologies.com" },
  { nome: "Fernando Fonseca de Souza", email: "fernando.fonseca.ext@ciriontechnologies.com" },
  { nome: "Luis Fernando Arias Roman", email: "luiz.roman.ext@ciriontechnologies.com" },
  { nome: "Marcos Gondim", email: "Marcos.gondim@ciriontechnologies.com" },
  { nome: "Rodrigo Neves", email: "rodrigo.neves.ext@ciriontechnologies.com" },
  { nome: "Luiz Fernando Coimbra Silva", email: "luiz.fernandocoimbrasilva@ciriontechnologies.com" },
  { nome: "Ellen Souza", email: "ellen.souza.ext@ciriontechnologies.com" },
  { nome: "Arthur Vieira", email: "arthur.vieira.ext@ciriontechnologies.com" },
  { nome: "Eduardo Conceicao", email: "eduardo.conceicao@ciriontechnologies.com" },
  { nome: "Alexandre Torejiani", email: "alexandre.tourejiane@ciriontechnologies.com" },
  { nome: "Jonathas Costa", email: "jonathas.costa@ciriontechnologies.com" },
  { nome: "Victor Hugo Borges Ribeiro Pedroso", email: "victor.borges.ext@ciriontechnologies.com" },
  { nome: "Antonio Oliveira da Silva Neto", email: "antonio.oliveiradasilvaneto.ext@ciriontechnologies.com" },
  { nome: "Amanda Pantaleão", email: "amanda.pantaleao.ext@ciriontechnologies.com" },
  { nome: "Adalberto Costa", email: "adalberto.costa@ciriontechnologies.com" },
  { nome: "Horacio Gustavo Cardona", email: "horacio.cardona@ciriontechnologies.com" },
  { nome: "Valter Gonçalves", email: "valter.goncalves@ciriontechnologies.com" },
  { nome: "Karina Bacelar", email: "karina.bacelar@ciriontechnologies.com" },
  { nome: "Diego Flefle", email: "diego.flefle@ciriontechnologies.com" },
  { nome: "Danilo Colichio Lino", email: "danilo.lino@ciriontechnologies.com" },
  { nome: "Edson Vieira Lamim", email: "edson.lamin.ext@ciriontechnologies.com" },
  { nome: "Igor Romero Molina", email: "igor.molina@ciriontechnologies.com" },
  { nome: "Roberto Cassiano", email: "roberto.cassiano@ciriontechnologies.com" },
  { nome: "Rummenigge Lima", email: "rummenigge.lima@ciriontechnologies.com" },
  { nome: "Andre Lima", email: "andre.lima@ciriontechnologies.com" },
  { nome: "PE04YP16", email: "andre.lima@ciriontechnologies.com" },
  { nome: "Eduardo Severino Silva", email: "eduardo.silva@ciriontechnologies.com" },
  { nome: "Eder gonçalves", email: "eder.goncalves@ciriontechnologies.com" },
  { nome: "Dirlei de Assis", email: "dirlei.deassis@ciriontechnologies.com" },
  { nome: "Heubert River", email: "heubert.river@ciriontechnologies.com" },
  { nome: "Elio Soares", email: "elio.soares.ext@ciriontechnologies.com" },
  { nome: "Fabiano Geraldo da Cruz", email: "fabiano.geraldodacruz@ciriontechnologies.com" },
  { nome: "Marcelo Moreira Florindo", email: "Marcelo.MoreiraFlorindo@ciriontechnologies.com" },
  { nome: "Pamela dos Santos Morais", email: "pamela.akamine@ciriontechnologies.com" },
  { nome: "Roberta Gouveia", email: "roberta.gouveia@ciriontechnologies.com" },
  { nome: "Rafael Rangel de Andrade", email: "rafael.rangeldeandrade@ciriontechnologies.com" },
  { nome: "Fabio Batista Pereira", email: "fabio.batistapereira@ciriontechnologies.com" },
  { nome: "Clóvis Prazeres De Lima", email: "clovis.prazeres@ciriontechnologies.com" },
  { nome: "Tiago Gimenez Olmedo", email: "tiago.olmedo@ciriontechnologies.com" },
  { nome: "Deivisson Pinheiro Pereira", email: "deivisson.pinheiro@ciriontechnologies.com" },
  { nome: "Fernando Bilbau Furtado", email: "fernando.bilbaufurtado@ciriontechnologies.com" },
  { nome: "Klebber Bassetto", email: "kleber.bassetto@ciriontechnologies.com" },
  { nome: "Fabio Rocha de Oliveira", email: "fabio.rochadeoliveira@ciriontechnologies.com" },
  { nome: "Bruno costa", email: "bruno.costa@ciriontechnologies.com" },
  { nome: "Windson Gomes Hora", email: "windson.gomeshora@ciriontechnologies.com" },
  { nome: "Diego Pereira", email: "diego.pereira@ciriontechnologies.com" },
  { nome: "Macleine Xavier de Souza", email: "macleine.souza@ciriontechnologies.com" },
  { nome: "Rafael de Almeida", email: "rafael.almeida@ciriontechnologies.com" },
  { nome: "James Lima", email: "James.Lima@ciriontechnologies.com" },
  { nome: "Andre Mendonça", email: "andre.mendonca@ciriontechnologies.com" },
  { nome: "Ivan Saide de Melo", email: "ivan.saidedemelo@ciriontechnologies.com" },
  { nome: "Sergio Mendonça", email: "sergio.mendonca@ciriontechnologies.com" },
  { nome: "Danilo Aparecido Gomes", email: "danilo.aparecidogomes@ciriontechnologies.com" },
  { nome: "Alexsandro Silva", email: "alexsandro.silva@ciriontechnologies.com" },
  { nome: "Jurandir Braz dos Santos Neto", email: "jurandir.braz@ciriontechnologies.com" },
  { nome: "Ederson Satyro Lopes", email: "ederson.satyrolopes@ciriontechnologies.com" },
  { nome: "Ronald Aguiar Garcia", email: "ronald.aguiargarcia@ciriontechnologies.com" },
  { nome: "Clemilson Silva", email: "clemilson.silva@ciriontechnologies.com" },
  { nome: "Douglas da Silva Mattos", email: "Douglas da Silva Mattos" },
  { nome: "Julia Paiva", email: "julia.paiva@ciriontechnologies.com" },
  { nome: "Juliana Tavares de Morais", email: "juliana.tavaresdemorais@ciriontechnologies.com" },
  { nome: "Bruno Aparecido de Oliveira Campos", email: "bruno.aparecidodeoliveira@ciriontechnologies.com" },
  { nome: "Andre Marcelino Miliani", email: "andre.marcelinomiliani@ciriontechnologies.com" },
  { nome: "Giovanna Ferreira Soares", email: "giovanna.ferreirasoares@ciriontechnologies.com" },
  { nome: "Thiago Donizeti Da Silva", email: "thiago.donizeti@ciriontechnologies.com" },
  { nome: "Rubens Hida", email: "rubens.hida.ext@ciriontechnologies.com" },
  { nome: "Flavio da Costa", email: "flavio.dacosta@ciriontechnologies.com" },
  { nome: "Alexandre Antunes", email: "alexandre.antunes@ciriontechnologies.com" },
  { nome: "Tiago Andre Rodrigues", email: "tiago.rodrigues.ext@ciriontechnologies.com" },
  { nome: "Caio Ferrari", email: "caio.ferrari@ciriontechnologies.com" },
  { nome: "Sthefanny Lima", email: "sthefanny.lima@ciriontechnologies.com" },
  { nome: "Valdir Freire", email: "valdir.freire@ciriontechnologies.com" },
  { nome: "Aline Gomes", email: "aline.gomes.ext@ciriontechnologies.com" },
  { nome: "Eder Onofre", email: "eder.onofre@ciriontechnologies.com" },
  { nome: "Murilo Almeida De Jesus", email: "murilo.almeidadejesus.ext@ciriontechnologies.com" },
  { nome: "kethelyn cavalari de souza", email: "kethelyn.cavalaridesouza@ciriontechnologies.com" },
  { nome: "Vlamir Maciel de Lima", email: "vlamir.maciel@ciriontechnologies.com" },
  { nome: "Thomaz Cortez Bertanha", email: "thomaz.cortezbertanha@ciriontechnologies.com" },
  { nome: "Mozair Costa", email: "mozair.costa@ciriontechnologies.com" },
  { nome: "Thiago Curimbaba Sampaio", email: "thiago.curimbabasampaio@ciriontechnologies.com" },
  { nome: "Adriano Oliveira", email: "adriano.oliveira.ext@ciriontechnologies.com" },
  { nome: "Anderson Santos oliveira", email: "anderson.santos.ext@ciriontechnologies.com" },
  { nome: "Esther Gimenez", email: "esther.gimenez@ciriontechnologies.com" },
  { nome: "Mauricio Tosta", email: "Mauricio.Tosta@ciriontechnologies.com" },
  { nome: "Fabio Da Silva De Oliveira", email: "fabio.oliveira@ciriontechnologies.com" },
  { nome: "Fernando Duarte", email: "fernando.duarte@ciriontechnologies.com" },
  { nome: "Cleverson Nazarete", email: "cleverson.nazarete@ciriontechnologies.com" },
  { nome: "Flavio Vieira Soares", email: "flavio.vieirasoares@ciriontechnologies.com" },
  { nome: "Samanha Bispo", email: "samantha.bispo@ciriontechnologies.com" },
  { nome: "Eliel Florencio de Mello", email: "eliel.florenciodemello@ciriontechnologies.com" },
  { nome: "Rafael Zeferino", email: "rafael.zeferino@ciriontechnologies.com" },
  { nome: "Claudia Secco", email: "claudia.secco@ciriontechnologies.com" },
  { nome: "Jose Eduardo Leao De Freitas", email: "Jose.Freitas@ciriontechnologies.com" },
  { nome: "Claudionor Filho", email: "claudionor.filho@ciriontechnologies.com" },
  { nome: "Elaine Penci", email: "elaine.penci@ciriontechnologies.com" },
  { nome: "Guilherme Rizzo", email: "guilherme.rizzo@ciriontechnologies.com" },
  { nome: "David Boscolo", email: "david.boscolo@ciriontechnologies.com" },
  { nome: "Rodrigo De Freitas Gallina", email: "Rodrigo.Gallina@ciriontechnologies.com" },
  { nome: "fernando duarte", email: "fernando.duarte@ciriontechnologies.com" },
  { nome: "Michelly de Mei", email: "michelly.demei@ciriontechnologies.com" },
  { nome: "Cira Crizostimo De Oliveira", email: "Cira.Oliveira@ciriontechnologies.com" },
  { nome: "Luiz Souza", email: "luiz.souza@ciriontechnologies.com" },
  { nome: "Marcus Pelegrini", email: "marcus.pelegrini@ciriontechnologies.com" },
  { nome: "Luighi Ferderle Ferreira", email: "luighi.ferderleferreira@ciriontechnologies.com" },
  { nome: "Adriano do Prado", email: "adriano.doprado.ext@ciriontechnologies.com" },
  { nome: "Emilly de Sousa", email: "emilly.desousa@ciriontechnologies.com" },
  { nome: "Rafael Narciso", email: "rafael.narciso@ciriontechnologies.com" },
  { nome: "Leonardo Oliveira Fuentes", email: "leonardo.oliveirafuentes@ciriontechnologies.com" },
  { nome: "Márcio Lima Ferreira", email: "marcio.limaferreira@ciriontechnologies.com" },
  { nome: "Beatriz Toni dos Santos", email: "beatriz.tonidossantos@ciriontechnologies.com" },
  { nome: "Gilberto Pinho Junior", email: "gilberto.pinhojunior@ciriontechnologies.com" },
  { nome: "Fernanda Santicioli Ramos", email: "fernanda.santicioliramos@ciriontechnologies.com" },
  { nome: "Fabiano Geraldo Da Cruz", email: "fabiano.geraldodacruz@ciriontechnologies.com" },
  { nome: "Leandro Lino", email: "leandro.lino@ciriontechnologies.com" },
  { nome: "Leandro Ductra", email: "leandro.ductra@ciriontechnologies.com" },
  { nome: "Saskia Vaz", email: "saskia.vaz@ciriontechnologies.com" },
  { nome: "Messias Francisco Da Silva", email: "messias.francisco.ext@ciriontechnologies.com" },
  { nome: "Moises Santana", email: "moises.santana.ext@ciriontechnologies.com" },
  { nome: "Ivan Saide de Melo", email: "ivan.melo@ciriontechnologies.com" },
  { nome: "Luis Matos", email: "luis.matos@ciriontechnologies.com" },
  { nome: "Carolina Alvarez Magioni", email: "carolina.alvarezmagioni@ciriontechnologies.com" },
  { nome: "Anderson Pagani", email: "anderson.pagani@ciriontechnologies.com" },
  { nome: "Bruno Balthazar Garcia", email: "bruno.garcia@ciriontechnologies.com" },
  { nome: "Luiz Filippe Andrade Dos Santos", email: "luiz.andrade@ciriontechnologies.com" },
  { nome: "Carlos Barbosa Rodrigues", email: "carlos.barbosarodrigues@ciriontechnologies.com" },
  { nome: "Cristiano Novaes de Oliveira", email: "cristiano.novaes@ciriontechnologies.com" },
  { nome: "Renan Da Silva Santos De Oliveira", email: "renan.santos.ext@ciriontechnologies.com" },
  { nome: "Carlos Eduardo Arruda Moraes", email: "carlos.arruda.ext@ciriontechnologies.com" },
  { nome: "Natã dos Santos Soares", email: "nata.dossantossoares@ciriontechnologies.com" },
  { nome: "JENNIFFER MARIA DOS SANTOS", email: "jennifer.santos@ciriontechnologies.com" },
  { nome: "Vinicius Mancini", email: "vinicius.mancini@ciriontechnologies.com" },
  { nome: "Caio Anastacio pereira", email: "caio.pereira@ciriontechnologies.com" },
  { nome: "Andre Miliani", email: "andre.miliani@ciriontechnologies.com" },
  { nome: "Rúbia Carolina Meira de Lima", email: "rubia.lima@ciriontechnologies.com" },
  { nome: "Vinicius Evangelista de Souza", email: "vinicius.desouza.ext@ciriontechnologies.com" },
  { nome: "Thiago Dias Almeida Santos", email: "thiago.diasalmeidasantos@ciriontechnologies.com" },
  { nome: "Isabelle Nunes De Souza Pereira", email: "isabelle.nunes.ext@ciriontechnologies.com" },
  { nome: "David Dela Nuwordu", email: "david.nuwordu@ciriontechnologies.com" },
  { nome: "Rodrigo Secco", email: "rodrigo.secco@ciriontechnologies.com" },
  { nome: "Alex Soares da Silva", email: "alex.soaresdasilva@ciriontechnologies.com" },
  { nome: "Bruno Aparecido de Oliveira", email: "bruno.aparecidodeoliveira@ciriontechnologies.com" },
  { nome: "Renato Juliano Ananias", email: "Renato.JulianoAnanias@ciriontechnologies.com" },
  { nome: "Gilberto Araujo", email: "gilberto.araujo.ext@ciriontechnologies.com" },
  { nome: "Marcos da Silva", email: "gilberto.araujo.ext@ciriontechnologies.com" },
  { nome: "Luciana Bardo de Azevedo", email: "luciana.bardo@ciriontechnologies.com" },
  { nome: "Evaldo Souza Costa", email: "evaldo.souzacosta@ciriontechnologies.com" },
  { nome: "Nivea Augusto", email: "nivea.augusto@ciriontechnologies.com" },
  { nome: "Eder Gonçalves", email: "eder.goncalves@ciriontechnologies.com" },
  { nome: "Jorge Pacheco", email: "Jorge.Pacheco@ciriontechnologies.com" }
];

export const MERCADO_PAGO_URL = import.meta.env.VITE_MERCADO_PAGO_URL || 'https://mpago.la/1CTeHzU';
